/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package view;
import controller.ArtistaController;
import model.Artista;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author dalfaro
 */
public class MainWindowGUI extends javax.swing.JFrame {

    
    
    private ArtistaController artistaController;

    /**
     * Creates new form MainWindowGUI
     */
    public MainWindowGUI() {
    initComponents();
    verificarConexionBD();
    artistaController = new ArtistaController();
    cargarArtistasEnTabla();
    inicializarAcciones();
    inicializarEventosTabla();
}
    
    
private void inicializarAcciones() {
    jButton_insertarArtista.addActionListener(e -> jButton_insertarArtistaActionPerformed(e));
    jButton_limpiarTextFields.addActionListener(e -> limpiarCampos());
    jButton_updatearArtista.addActionListener(e -> jButton_updatearArtistaActionPerformed(e));
}


    
    private void inicializarEventosTabla() {
    jTable_artistas.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = jTable_artistas.getSelectedRow();
            if (fila >= 0) {
                jTextField_NombreArtista.setText(jTable_artistas.getValueAt(fila, 1).toString());
                jTextField_GeneroArtista.setText(jTable_artistas.getValueAt(fila, 2).toString());
                jTextField_paisOrigenArtista.setText(jTable_artistas.getValueAt(fila, 3).toString());
            }
        }
    });
}
    private void verificarConexionBD() {
    try {
        java.sql.Connection conn = util.DatabaseConnection.getConnection();

        if (conn != null && !conn.isClosed()) {
            JOptionPane.showMessageDialog(
                    this,
                    "✔ Conexión exitosa a Oracle.",
                    "Estado de conexión",
                    JOptionPane.INFORMATION_MESSAGE
            );
            conn.close();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "✖ No se pudo conectar a Oracle.",
                    "Estado de conexión",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "✖ Error de conexión:\n" + e.getMessage(),
                "Estado de conexión",
                JOptionPane.ERROR_MESSAGE
        );
    }
}

    private void inicializarEventos() {

    jTable_artistas.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int fila = jTable_artistas.getSelectedRow();
            if (fila >= 0) {
                jTextField_NombreArtista.setText(jTable_artistas.getValueAt(fila, 1).toString());
                jTextField_GeneroArtista.setText(jTable_artistas.getValueAt(fila, 2).toString());
                jTextField_paisOrigenArtista.setText(jTable_artistas.getValueAt(fila, 3).toString());
            }
        }
    });

    jButton_insertarArtista.addActionListener(evt -> jButton_insertarArtistaActionPerformed(evt));
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_inicioGlobal = new javax.swing.JPanel();
        jlabel_tituloInicio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_InicioDescripcion = new javax.swing.JTextArea();
        jPanel_ArtistaGlobal = new javax.swing.JPanel();
        jPanel_DatosdelArtista = new javax.swing.JPanel();
        jTextField_NombreArtista = new javax.swing.JTextField();
        jTextField_GeneroArtista = new javax.swing.JTextField();
        jTextField_paisOrigenArtista = new javax.swing.JTextField();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_genero = new javax.swing.JLabel();
        jLabel_paisDeOrigen = new javax.swing.JLabel();
        jButton_insertarArtista = new javax.swing.JButton();
        jButton_updatearArtista = new javax.swing.JButton();
        jButton_borrarArtista = new javax.swing.JButton();
        jButton_limpiarTextFields = new javax.swing.JButton();
        jScrollPane_panelDetabla = new javax.swing.JScrollPane();
        jTable_artistas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabel_tituloInicio.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlabel_tituloInicio.setText("Sistema de gestion de eventos y conciertos");

        jTextArea_InicioDescripcion.setEditable(false);
        jTextArea_InicioDescripcion.setColumns(20);
        jTextArea_InicioDescripcion.setRows(5);
        jTextArea_InicioDescripcion.setText("Bienvenido al Sistema de Gestión de Eventos y Conciertos\n\nEste sistema permite:\n  - Gestionar artistas, eventos y locaciones\n  - Administrar entradas y asistentes\n  - Generar reportes y estadísticas\n  - Control completo mediante base de datos Oracle\n\nSeleccione una pestaña para comenzar.\n\nProyecto Final - SC-504 Lenguaje de Base de Datos\nUniversidad Fidélitas - III Cuatrimestre 2025");
        jScrollPane1.setViewportView(jTextArea_InicioDescripcion);

        javax.swing.GroupLayout jPanel_inicioGlobalLayout = new javax.swing.GroupLayout(jPanel_inicioGlobal);
        jPanel_inicioGlobal.setLayout(jPanel_inicioGlobalLayout);
        jPanel_inicioGlobalLayout.setHorizontalGroup(
            jPanel_inicioGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inicioGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inicioGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_inicioGlobalLayout.createSequentialGroup()
                        .addComponent(jlabel_tituloInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(94, Short.MAX_VALUE))))
        );
        jPanel_inicioGlobalLayout.setVerticalGroup(
            jPanel_inicioGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inicioGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel_tituloInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inicio", jPanel_inicioGlobal);

        jPanel_DatosdelArtista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        jLabel_nombre.setText("Nombre:");

        jLabel_genero.setText("Género:");

        jLabel_paisDeOrigen.setText("País de Origen:");

        jButton_insertarArtista.setText("Insertar");

        jButton_updatearArtista.setText("Update");

        jButton_borrarArtista.setText("Delete");
        jButton_borrarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrarArtistaActionPerformed(evt);
            }
        });

        jButton_limpiarTextFields.setText("Limpiar");

        javax.swing.GroupLayout jPanel_DatosdelArtistaLayout = new javax.swing.GroupLayout(jPanel_DatosdelArtista);
        jPanel_DatosdelArtista.setLayout(jPanel_DatosdelArtistaLayout);
        jPanel_DatosdelArtistaLayout.setHorizontalGroup(
            jPanel_DatosdelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DatosdelArtistaLayout.createSequentialGroup()
                .addGroup(jPanel_DatosdelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_DatosdelArtistaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton_insertarArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_DatosdelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_DatosdelArtistaLayout.createSequentialGroup()
                                .addComponent(jButton_updatearArtista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_borrarArtista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_limpiarTextFields)
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addGroup(jPanel_DatosdelArtistaLayout.createSequentialGroup()
                                .addGroup(jPanel_DatosdelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_paisDeOrigen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel_DatosdelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_paisOrigenArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jTextField_GeneroArtista)))))
                    .addGroup(jPanel_DatosdelArtistaLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel_nombre)
                        .addGap(47, 47, 47)
                        .addComponent(jTextField_NombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(545, 545, 545))
        );
        jPanel_DatosdelArtistaLayout.setVerticalGroup(
            jPanel_DatosdelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DatosdelArtistaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel_DatosdelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_NombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_DatosdelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_GeneroArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_genero))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DatosdelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_paisOrigenArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_paisDeOrigen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel_DatosdelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_insertarArtista)
                    .addComponent(jButton_updatearArtista)
                    .addComponent(jButton_borrarArtista)
                    .addComponent(jButton_limpiarTextFields))
                .addGap(31, 31, 31))
        );

        jTable_artistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Género", "País de origen", "Fecha de creación"
            }
        ));
        jScrollPane_panelDetabla.setViewportView(jTable_artistas);

        javax.swing.GroupLayout jPanel_ArtistaGlobalLayout = new javax.swing.GroupLayout(jPanel_ArtistaGlobal);
        jPanel_ArtistaGlobal.setLayout(jPanel_ArtistaGlobalLayout);
        jPanel_ArtistaGlobalLayout.setHorizontalGroup(
            jPanel_ArtistaGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_DatosdelArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_ArtistaGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_panelDetabla))
        );
        jPanel_ArtistaGlobalLayout.setVerticalGroup(
            jPanel_ArtistaGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ArtistaGlobalLayout.createSequentialGroup()
                .addComponent(jPanel_DatosdelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_panelDetabla, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Artistas", jPanel_ArtistaGlobal);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eventos", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reportes", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Auditoria", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_borrarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_borrarArtistaActionPerformed
    String input = JOptionPane.showInputDialog(
            this,
            "Ingrese el ID del artista que desea eliminar:",
            "Eliminar Artista",
            JOptionPane.QUESTION_MESSAGE
    );

    if (input == null) {
        return;
    }

    input = input.trim();
    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Debe ingresar un ID válido.",
                "Advertencia",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    try {
        int idArtista = Integer.parseInt(input);

        boolean eliminado = artistaController.eliminarArtista(idArtista);

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Artista eliminado correctamente.");
            cargarArtistasEnTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el artista o no pudo eliminarse.",
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.",
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton_borrarArtistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new MainWindowGUI().setVisible(true);
            }
        });
        
        
    }
    private void cargarArtistasEnTabla() {
    DefaultTableModel model = (DefaultTableModel) jTable_artistas.getModel();
    model.setRowCount(0);

    for (Artista artista : artistaController.listarArtistas()) {
        model.addRow(new Object[]{
            artista.getIdArtista(),
            artista.getNombre(),
            artista.getGeneroMusical(),
            artista.getPaisOrigen(),
            artista.getFechaCreacion()
        });
    }
}
    
    private void jButton_updatearArtistaActionPerformed(java.awt.event.ActionEvent evt) {                                                         
    int fila = jTable_artistas.getSelectedRow();
    
    if (fila < 0) {
        JOptionPane.showMessageDialog(this,
                "Debe seleccionar un artista de la tabla para actualizar.",
                "Advertencia",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int id = Integer.parseInt(jTable_artistas.getValueAt(fila, 0).toString());
        String nombre = jTextField_NombreArtista.getText().trim();
        String genero = jTextField_GeneroArtista.getText().trim();
        String pais = jTextField_paisOrigenArtista.getText().trim();

        if (nombre.isEmpty() || genero.isEmpty() || pais.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
            return;
        }

        Artista artista = new Artista();
        artista.setIdArtista(id);
        artista.setNombre(nombre);
        artista.setGeneroMusical(genero);
        artista.setPaisOrigen(pais);

        if (artistaController.actualizarArtista(artista)) {
            JOptionPane.showMessageDialog(this, "Artista actualizado correctamente.");
            cargarArtistasEnTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el artista.");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, 
                "Error al actualizar: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    limpiarCampos();
}
    
    private void jButton_insertarArtistaActionPerformed(java.awt.event.ActionEvent evt) {                                                         
    String nombre = jTextField_NombreArtista.getText().trim();
    String genero = jTextField_GeneroArtista.getText().trim();
    String pais = jTextField_paisOrigenArtista.getText().trim();

    if (nombre.isEmpty() || genero.isEmpty() || pais.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
        return;
    }

    Artista artista = new Artista();
    artista.setNombre(nombre);
    artista.setGeneroMusical(genero);
    artista.setPaisOrigen(pais);

    if (artistaController.insertarArtista(artista)) {
        JOptionPane.showMessageDialog(this, "Artista insertado exitosamente");
        cargarArtistasEnTabla();
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(this, "Error al insertar artista");
    }
}
    
    private void limpiarCampos() {
    jTextField_NombreArtista.setText("");
    jTextField_GeneroArtista.setText("");
    jTextField_paisOrigenArtista.setText("");
}

    private void jButton_limpiarTextFieldsActionPerformed(java.awt.event.ActionEvent evt) {                                                         
    limpiarCampos();
}
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_borrarArtista;
    private javax.swing.JButton jButton_insertarArtista;
    private javax.swing.JButton jButton_limpiarTextFields;
    private javax.swing.JButton jButton_updatearArtista;
    private javax.swing.JLabel jLabel_genero;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_paisDeOrigen;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_ArtistaGlobal;
    private javax.swing.JPanel jPanel_DatosdelArtista;
    private javax.swing.JPanel jPanel_inicioGlobal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_panelDetabla;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_artistas;
    private javax.swing.JTextArea jTextArea_InicioDescripcion;
    private javax.swing.JTextField jTextField_GeneroArtista;
    private javax.swing.JTextField jTextField_NombreArtista;
    private javax.swing.JTextField jTextField_paisOrigenArtista;
    private javax.swing.JLabel jlabel_tituloInicio;
    // End of variables declaration//GEN-END:variables
}
